# Generated by Django 3.2.3 on 2021-05-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='funders_id',
            field=models.ManyToManyField(blank=True, related_name='funds', to='core.FundSources'),
        ),
    ]
