# Generated by Django 3.2.3 on 2021-05-23 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organizations_funders_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('site', models.URLField(unique=True)),
                ('funding_possibility', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Competitor', 'Competitor'), ('Neutral', 'Neutral'), ('Market', 'Market'), ('Vendor', 'Vendor')], default='Neutral', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('site', models.URLField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('funder', models.ManyToManyField(blank=True, related_name='funder', to='core.FundSource')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('features', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('parent_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_org', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('parent_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategy_org', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Initiatives',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='funders_id',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='SocialPosts',
        ),
        migrations.DeleteModel(
            name='Strategies',
        ),
        migrations.DeleteModel(
            name='FundSources',
        ),
        migrations.DeleteModel(
            name='Organizations',
        ),
        migrations.AddField(
            model_name='strategy',
            name='related_tag',
            field=models.ManyToManyField(blank=True, related_name='strategy_tag', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='followed_strategy',
            field=models.ManyToManyField(blank=True, related_name='post_strategy', to='core.Strategy'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='parent_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_org', to='core.organization'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='related_tag',
            field=models.ManyToManyField(blank=True, related_name='post_tag', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_tag',
            field=models.ManyToManyField(blank=True, related_name='product_tag', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='organization',
            name='related_tag',
            field=models.ManyToManyField(blank=True, related_name='org_tag', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='followed_strategy',
            field=models.ManyToManyField(blank=True, related_name='initiative_strategy', to='core.Strategy'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='parent_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_org', to='core.organization'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='related_tag',
            field=models.ManyToManyField(blank=True, related_name='initiative_tag', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='fundsource',
            name='related_tag',
            field=models.ManyToManyField(blank=True, related_name='funder_tag', to='core.Tag'),
        ),
    ]
