# Generated by Django 3.2.3 on 2021-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
