# Generated by Django 3.2.3 on 2021-05-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_consumer_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
