# Generated by Django 3.2.3 on 2021-06-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210527_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default='https://abc.xyz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='related_tag',
            field=models.ManyToManyField(related_name='product_tag', to='core.Tag'),
        ),
    ]
