# Generated by Django 3.2.3 on 2021-08-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210601_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_org',
            field=models.CharField(max_length=100),
        ),
    ]
